apiVersion: v1
kind: Service
metadata:
  name: camel-challenge
  namespace: demo
spec:
  selector:
    app: camel-challenge
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
